### ISSUE TITLE
ticker is unable to smoothly transition during resize

### ISSUE THREAD

**Issue by UnsungHero97** [robinhood/ticker#63] opened 2017-09-27 18:06 UTC
OnePlus One A0001
Android 6.0.1
Cyanogen OS 13.1.2

There's a bug that impacts the smoothness of the animations/transitions. It happens when the ticker needs to resize the dollar value string, for example, when it transitions from above $100 to below $100, or from above $10 to below $10. I've recorded a video of my screen to demonstrate the issue on my device:

https://www.dropbox.com/s/y4k3f3u6jb3wulm/device-2017-09-21-104722.mp4

This has been happening for well over a year, maybe longer. When will this be resolved?

**Comment by jinatonic** [comment] 2017-09-27 20:42
Hello,

Thanks for filing the issue. This is actually not a problem with ticker (well, I guess it technically is), but it's because on the robinhood app there are simply too many data points on the 1Y graph. So when you hold down your finger at one point, the data under your finger continuously changes among 2 or 3 values which means ticker tries to animate from X to A then B then A then B then A etc. and never finishes the animation. 

But yeah, we should fix that issue on robinhood side to buffer input events once you start scrubbing the graph. I'll try to get it in for a near future release.

**Comment by UnsungHero97** [comment] 2017-09-27 21:34
The issue is reproducible on the 1D graph as well.

I just checked the Workday stock `WDAY` for today, and it drops below $100 around 10:10am, as well as around 12:50pm. The issue is reproducible at those dips. Let me know if you need a screen recording to demonstrate.

**Comment by jinatonic** [comment] 2017-09-27 21:41
oh interesting, you are right, ill look into this.

**Comment by jinatonic** [comment] 2017-09-27 22:23
The issue is fixed in robinhood and will be included in the next app update.

**Comment by UnsungHero97** [comment] 2017-09-27 22:32
Sweet! Thanks for the quick turnaround on this! Can't wait for the next app update to come through!

**Comment by danh32** [comment] 2017-09-28 01:53
I wonder if it's worth adding a safeguard in ticker as well? Like no-op the `setText()` call if we're already animating to the same value?

**Comment by jinatonic** [comment] 2017-09-28 16:56
haha good point. this was actually supported by the library but one of my refactors on how tickercolumn works must have broke it.

**Closed** 2017-09-28 18:08 UTC
